backend/models/TrainingType.php
<?php

namespace backend\models;

use Yii;
use \backend\models\base\TrainingType as BaseTrainingType;

/**
 * This is the model class for table "training_type".
 */
class TrainingType extends BaseTrainingType
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['type'], 'required'],
            [['lock', 'created_by', 'updated_by', 'deleted_by', 'created', 'modified', 'deleted'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['type'], 'string', 'max' => 255],
            [['lock'], 'default', 'value' => '0'],
            [['lock'], 'mootensai\components\OptimisticLockValidator']
        ]);
    }
	
}

common/models/School.php
<?php

namespace common\models;

use \common\models\base\School as BaseSchool;

/**
 * This is the model class for table "school".
 */
class School extends BaseSchool
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['name', 'city'], 'required'],
            [['coordinates', 'remarks'], 'string'],
            [['has_en', 'lock', 'created_by', 'updated_by', 'deleted_by', 'created', 'modified', 'deleted', 'active'], 'integer'],
            [['logo', 'created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name', 'street', 'city', 'www', 'email', 'phone', 'contact_person'], 'string', 'max' => 255],
            [['street_no', 'post_code'], 'string', 'max' => 12],
            ['country_id', 'string', 'max' => 3],
            ['country_id', 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Country::className(), 'targetAttribute' => ['country_id' => 'id']],
            [['lock'], 'default', 'value' => '0'],
            [['lock'], 'mootensai\components\OptimisticLockValidator']
        ]);
    }



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        return $this->hasOne(\backend\models\Country::className(), ['id' => 'country_id']);
    }
	
}

backend/controllers/TrainingController.php
<?php

namespace backend\controllers;

use backend\models\Aircraft;
use backend\models\Simulator;
use backend\models\UserToSchool;
use backend\models\base\TrainingStartDates;
use Yii;
use backend\models\Training;
use backend\models\TrainingSearch;
use backend\models\School;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json,
    yii\data\ArrayDataProvider,
    kartik\mpdf\Pdf;
use yii2mod\rbac\filters\AccessControl;

/**
 * TrainingController implements the CRUD actions for Training model.
 */
class TrainingController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'allowActions' => [
                    // The actions listed here will be allowed to everyone including guests.
                ]
            ],
            'access2' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['update', 'view', 'delete', 'duplicate'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['update', 'view', 'delete', 'duplicate'],
                        'matchCallback' => function($rule, $action) {
                            if (\webvimark\modules\UserManagement\models\User::hasRole('school-admin', false))
                            {
                                return UserToSchool::validateUserToTraining(Yii::$app->request->get('id'), Yii::$app->user->id);
                            } else {
                                return true;
                            }
                        }
                    ],
                ],
            ],
            'access3' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['create'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'matchCallback' => function($rule, $action) {
                            if (\webvimark\modules\UserManagement\models\User::hasRole('school-admin', false))
                            {
                                return UserToSchool::validateUserToSchool(Yii::$app->request->get('school_id'), Yii::$app->user->id);
                            } else {
                                return true;
                            }
                        }
                    ],
                ],
            ]
        ];
    }

    /**
     * Lists all Training models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TrainingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
		if (Yii::$app->request->post('hasEditable')) {
			// instantiate your book model for saving
			$ID = Yii::$app->request->post('editableKey');
			$model = Training::findOne($ID);

			// store a default json response as desired by editable
			$out = Json::encode(['output'=>'', 'message'=>'']);

			// fetch the first entry in posted data (there should only be one entry 
			// anyway in this array for an editable submission)
			// - $posted is the posted data for Book without any indexes
			// - $post is the converted array for single model validation
			$posted = current($_POST['Training']);
			$post = ['Training' => $posted];

			// load model like any single model validation
			if ($model->load($post)) {
			// can save model or do something before saving model
			$model->save();

			// custom output to return to be displayed as the editable grid cell
			// data. Normally this is empty - whereby whatever value is edited by
			// in the input by user is updated automatically.
			$output = '';

			// specific use case where you need to validate a specific
			// editable column posted when you have more than one
			// EditableColumn in the grid view. We evaluate here a
			// check to see if buy_amount was posted for the Book model
			/*
			if (isset($posted['buy_amount'])) {
			$output = Yii::$app->formatter->asDecimal($model->buy_amount, 2);
			}
			*/

			// similarly you can check if the name attribute was posted as well
			// if (isset($posted['name'])) {
			// $output = ''; // process as you need
			// }
			$out = Json::encode(['output'=>$output, 'message'=>'']);
			}
			// return ajax json encoded response and exit
			//echo $out;
			return $out;
		}

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Duplicate training record
     * @param integer $id
     * @return mixed
     */
    public function actionDuplicate($id)
    {
        $model = $this->findModel($id);
        $duplicated = new Training();
        $duplicated->attributes = $model->attributes;
        $duplicated->save();

        return $this->redirect(['update', 'id' => $duplicated->id]);
    }

    /**
     * Displays a single Training model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $providerAircraftToTraining = new \yii\data\ArrayDataProvider([
            'allModels' => $model->aircraft,
        ]);
        $providerSimulatorToTraining = new \yii\data\ArrayDataProvider([
            'allModels' => $model->simulator,
        ]);

        $providerStartDate= new \yii\data\ArrayDataProvider([
            'allModels' => $model->startDates
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'providerAircraftToTraining' => $providerAircraftToTraining,
            'providerSimulatorToTraining' => $providerSimulatorToTraining,
            'providerStartDate' => $providerStartDate,
        ]);
    }

    /**
     * Creates a new Training model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Training();
		if (isset($_GET['school_id']))
		{
			$school = School::findOne($_GET['school_id']);
			$model->school_id = $school->id;
			$school_name = $school->name;
		} else {
			$school_name = '';
		}
        if ($model->loadAll(Yii::$app->request->post()) && $model->save()) {
            foreach (Yii::$app->request->post('TrainingTranslation', []) as $language => $data) {
                foreach ($data as $attribute => $translation) {
                    $model->translate($language)->$attribute = $translation;
                }
                $model->translate($language)->training_id = $model->id;
                $model->translate($language)->save();
            }
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
			if (isset($_GET['school_id'])) $model->school_id = $_GET['school_id'];
            return $this->render('create', [
                'model' => $model,
                'school_name' => $school_name,
            ]);
        }
    }

    /**
     * Updates an existing Training model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		if ($school = School::findOne($model->school_id))
		{
			$school_name = $school->name;
		} else {
			$school_name = '';
		}

        $providerStartDate= new \yii\data\ArrayDataProvider([
            'allModels' => $model->startDates,
            'pagination' => [
                'pageSize' => -1
            ]
        ]);

        $providerAircraftToTraining = new \yii\data\ArrayDataProvider([
            'allModels' => $model->aircraft,
            'pagination' => [
                'pageSize' => -1
            ]
        ]);

        $providerSimulatorToTraining = new \yii\data\ArrayDataProvider([
            'allModels' => $model->simulator,
            'pagination' => [
                'pageSize' => -1
            ]
        ]);
		
        if ($model->loadAll(Yii::$app->request->post())) {



            if ($model->save()) {

                $tmp = array();
                $post = Yii::$app->request->post();
                if (isset($post['Aircraft'])){
                    foreach ($post['Aircraft'] as $a)
                    {
                        $tmp[] = $a['id'];
                    }
                }
                $aircrafts = Aircraft::find()->where(['in', 'id', $tmp])->all();
                $model->linkAll('aircraft', $aircrafts, [], true, true);

                $tmp = array();
                if (isset($post['Simulator'])){
                    foreach ($post['Simulator'] as $a)
                    {
                        $tmp[] = $a['id'];
                    }
                }
                $simulator = Simulator::find()->where(['in', 'id', $tmp])->all();
                $model->linkAll('simulator', $simulator, [], true, true);


                $tmp = array();
                foreach($model->startDates as $sd)
                {
                    $sd->start_date = \DateTime::createFromFormat('Y-m-d', $sd->start_date)->format('Y-m-d');
                    $sd->training_id = $model->id;
                    $sd->save();
                    $tmp[] = $sd->id;
                }
                //print_r(Yii::$app->request->post()['StartDates']);
                if (!isset(Yii::$app->request->post()['StartDates']))
                {
                    TrainingStartDates::deleteAll(['=', 'training_id', $model->id]);
                }

frontend/controllers/TrainingController.php
<?php
namespace frontend\controllers;

use Yii;
//use yii\base\InvalidParamException;
use yii\web\NotFoundHttpException;
use yii\web\Controller,
    yii\data\ArrayDataProvider;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
//use common\models\LoginForm;
use common\models\Training;
use frontend\models\TrainingSearch;
//use frontend\models\PasswordResetRequestForm;
//use frontend\models\ResetPasswordForm;
//use frontend\models\SignupForm;
use frontend\models\SchoolContactForm,
    frontend\models\SchoolRates;

/**
 * Site controller
 */
class TrainingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new TrainingSearch();
        $trainingsDataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $md5 = md5(serialize($searchModel));
        if(\Yii::$app->request->post('md5', null) != null){
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return ['md5'=>$md5];
        }

		return $this->render('index', [
            'searchModel' => $searchModel,
            'trainingsDataProvider' => $trainingsDataProvider,
            'md5'=>$md5
        ]);
    }

    /**
     * Displays a single Training model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if(!$model = $this->findModel($id)){
            $this->redirect(['/training/index']);
        }

        $ContactForm = new SchoolContactForm();
        if ($ContactForm->load(Yii::$app->request->post())) {
            if ($ContactForm->validate() && $ContactForm->sendEmail($model)) {
                Yii::$app->session->setFlash('success', Yii::t('frontend/training', 'Thank you for contacting us. We will respond to you as soon as possible.'));
                return $this->redirect(['training/view','id'=>$model->id]);
            } else {
                Yii::$app->session->setFlash('warning', Yii::t('frontend/training', 'There was an error sending email.'));
            }
            //return $this->refresh();
            //print_r($ContactForm);
        }



        $SchoolRatesForm = new SchoolRates();

        if(!\Yii::$app->user->isGuest){
            $SchoolRatesForm->user_id = \Yii::$app->user->id;
            $SchoolRatesForm->email = \Yii::$app->user->identity->email;

            $user = \Yii::$app->user->identity;
            if ($user->profile != null)
            {
                $SchoolRatesForm->name = $user->profile->username;
                $ContactForm->phone = $user->profile->phone;
                $ContactForm->name = $user->profile->username;
            }
            $ContactForm->email = \Yii::$app->user->identity->email;

        }

        $SchoolRatesForm->school_id = $model->school_id;
        $SchoolRatesForm->training_id = $model->id;

        if ($SchoolRatesForm->load(Yii::$app->request->post()) && $SchoolRatesForm->validate()) {
            if($SchoolRatesForm->save()){
                $SchoolRatesForm->text = '';
                $SchoolRatesForm->name = '';
                $SchoolRatesForm->email = '';
                Yii::$app->session->setFlash('success', Yii::t('frontend/training', 'Thank you for your review'));
                return $this->redirect(['training/view','id'=>$model->id]);
            }else
                Yii::$app->session->setFlash('warning', Yii::t('frontend/training', 'Error. Your review was not added.'));
        }

        //Yii::$app->session->setFlash('success', Yii::t('frontend/training', 'Thank you for your review'));

        $providerAircraftToTraining = new ArrayDataProvider([
            'allModels' => $model->aircraft,
        ]);

        return $this->render('view', [
            'model' => $model,
            'ContactForm' => $ContactForm,
            'providerAircraftToTraining' => $providerAircraftToTraining,
            'schoolRatesForm'=>$SchoolRatesForm
        ]);
    }

    /**
     * Finds the Training model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Training the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Training::find()->where(['training.id'=>$id, 'training.deleted'=>0])->joinWith('licenseType')->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('frontend/training', 'The requested page does not exist.'));
        }
	}
}

frontend/views/training/_map.php
<div class="container">
	<div class="row">
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;

$trainingsDataProvider->pagination->pageSize = 1000;
$locations = array();
$i = 0;

foreach($trainingsDataProvider->models as $model){
	$a_t = count($model->aircraft)>0 ? $model->aircraft[0]->aircraftType->name : "";

	if($model->address_practice_id > 0){
		$i++;
		$coord = explode(",", $model->addressPractice->coordinates);
		if (is_array($coord) && count($coord)>=2)
		{
			$start_text = '';
			if(is_array($model->startDates)){
				$date = null;
				foreach ($model->startDates as $termin){
					if($termin->start_date>=date('Y-m-d')){
						$date = $termin;
						break;
					}
				}
				$start_text = is_object($date) ? $date->start_text : Yii::t('training/view', 'Contact us');
			}else{
				$start_text = Yii::t('training/view', 'od zaraz');
			}

			$locations[$i]= [
				0=>($model->name),
				1=>($model->price),
				2=>$start_text,
				3=>($model->addressPractice->address.', '.$model->addressPractice->{'zip-code'}.' '.$model->addressPractice->city),
				4=>($a_t),
				5=>($model->elearning_hours + $model->theory_hours),
				6=>($model->aircraft_hours + $model->simulator_hours),
				7=>trim($coord[0]),
				8=>trim($coord[1]),
				9=>$model->school->logo,
				10=>(Url::to(['training/view', 'id' => $model->id])),
				11=>$model->id,
			];

		}

	}

	if($model->address_theory_id != $model->address_practice_id && $model->address_theory_id > 0){
		$i++;
		$coord = explode(",", $model->addressTheory->coordinates);
		if (is_array($coord) && count($coord)>=2)
		{
			$start_text = '';
			if(is_array($model->startDates)){
				$date = null;
				foreach ($model->startDates as $termin){
					if($termin->start_date>=date('Y-m-d')){
						$date = $termin;
						break;
					}
				}
				$start_text = is_object($date) ? $date->start_text : Yii::t('training/view', 'Contact us');
			}else{
				$start_text = Yii::t('training/view', 'od zaraz');
			}
			$locations[$i]= [
				0=>($model->name),
				1=>($model->price),
				2=>$start_text,
				3=>($model->addressTheory->address.', '.$model->addressTheory->{'zip-code'}.' '.$model->addressTheory->city),
				4=>($a_t),
				5=>($model->elearning_hours + $model->theory_hours),
				6=>($model->aircraft_hours + $model->simulator_hours),
				7=>trim($coord[0]),
				8=>trim($coord[1]),
				9=>$model->school->logo,
				10=>(Url::to(['training/view', 'id' => $model->id])),
				11=>$model->id,
			];
		}

	}

	if($model->address_practice_id > 0 || $model->address_theory_id > 0)
	echo Html::tag('div', str_ireplace(["\n", "\r", "\t"], "", Yii::$app->view->renderFile(__DIR__.'/_trainingGrid.php', ['model'=>$model])), ['class'=>'hidden to_map col-lg-4 col-sm-6 col-md-4 col-xs-12 item grid', 'id'=>'info_window_'.$model->id, 'data-id'=>$model->id]);
}
?>
</div>
</div>

	<div id="mapa-div" style="height:780px; padding:0px;"></div>
	<div id="locationsHF" class="hidden">
		<?= json_encode($locations); ?>
	</div>

frontend/views/training/_trainingGrid.php
<?php
use yii\helpers\Html,
	yii\helpers\HtmlPurifier,
	imanilchaudhari\CurrencyConverter\CurrencyConverter;

	$converter = new CurrencyConverter();
?>

<div class="thumbnail">
	<div class="clearfix">
		<?php if(!empty($model->school->logo)): ?>
			<?= Html::img($model->school->LogoResize(125), ['class'=>'pull-left', 'style'=>'max-height:52px;max-width: 95px;']) ?>
		<?php endif; ?>
		<h2 class="pull-right text-right"><?= number_format(($model->school->country->currency_id!=Yii::$app->params['currency'] ? $converter->convert($model->school->country->currency_id, Yii::$app->params['currency'], $model->price) : $model->price), 0, '.', '<span class="numspan"></span>') ?><span><?= Yii::$app->params['currency'] ?></span></h2>
	</div>
	<div class="clearfix title-box">
		<h3><?= Html::a($model->name, ['training/view', 'id' => $model->id], ['data-pjax'=>'0']) ?></h3>
		<div class="school-ratings">
			<span class="star-ratings-sprite">
				<span style="width:<?= $model->school_rate*100/5 ?>%" class="star-ratings-sprite-rating"></span>
			</span>
			<?= number_format(floatval($model->school_rate), 1, '.', ''); ?>
		</div>
	</div>
	<table class="details">
		<tr>
			<th>
				<?= Yii::t('training/view', 'Termin:'); ?>
			</th>
			<td>
				<?php
				if(is_array($model->startDates)){
					$date = null;
					foreach ($model->startDates as $termin){
						if($termin->start_date>=date('Y-m-d')){
							$date = $termin;
							break;
						}
					}
					echo is_object($date) ? $date->start_text : Yii::t('training/view', 'Contact us');
				}else{
					echo Yii::t('training/view', 'od zaraz');
				}
				?>
			</td>
		</tr>
		<tr>
			<th>
				<?= Yii::t('training/view', 'Miasto:'); ?>
			</th>
			<td>
				<span><?= HtmlPurifier::process($model->address_practice_id != 0 ? $model->addressPractice->city : ($model->address_theory_id != 0 ? $model->addressTheory->city : '-')) ?></span>&nbsp;
			</td>
		</tr>
		<?php if (count($model->aircraft) != 0 || count($model->simulator) != 0) : ?>
		<tr>
			<th>
				<?php
				if (count($model->aircraft) == 0 && count($model->simulator) > 0) {
					echo Yii::t('training/view', 'Simulator:');
				} else
					echo Yii::t('training/view', 'Aircraft:');
				?>
			</th>
			<td>
					<span>
						<?php
						if (count($model->aircraft) == 0 && count($model->simulator) > 0) {
							echo trim($model->simulator[0]->type);
						} else {
							if (count($model->aircraft) > 0) {
								echo trim($model->aircraft[0]->aircraftType->name);
							} else {
								echo "-";
							}
						}
						?>
					</span>&nbsp;
			</td>
		</tr>

		<?php endif; ?>

		<?php if(($model->elearning_hours + $model->theory_hours) > 0): ?>
			<tr>
				<th>
					<?= Yii::t('training/view', 'Teoria:'); ?>
				</th>
				<td>
					<?= ($model->elearning_hours + $model->theory_hours) ?>h
				</td>
			</tr>
		<?php endif; ?>

		<?php if(($model->aircraft_hours + $model->simulator_hours) > 0): ?>
		<tr>
			<th>
				<?= Yii::t('training/view', 'Praktyka:'); ?>
			</th>
			<td>
				<?= ($model->aircraft_hours + $model->simulator_hours) ?>h
			</td>
		</tr>
		<?php endif; ?>

	</table>
	<div class="col-lg-12 col-md-12 col-sm-12  col-xs-12 text-center extraTopMargin buttonCnt">

			<?= Html::a(Yii::t('training/view', 'Szczegóły'), ['training/view', 'id' => $model->id], ['class' => 'btn btn-primary text-uppercase', 'data-pjax'=>'0']) ?>

	</div>
</div>

frontend/views/training/_trainingList.php
<?php
use yii\helpers\Html,
	yii\helpers\HtmlPurifier,
	imanilchaudhari\CurrencyConverter\CurrencyConverter;

	$converter = new CurrencyConverter();
?>


<div class="col-lg-12">
	<div class="thumbail bg-white">
	<div class="row">
		<div class="col-sm-2 hidden-sm text-center">
			<?php if(!empty($model->school->logo)): ?>
				<img src="<?= $model->school->LogoResize(103) ?>" />
			<?php endif; ?>
		</div>
		<div class="col-sm-3">
			<h3><?= Html::a($model->name, ['training/view', 'id' => $model->id], ['data-pjax'=>'0']) ?></h3>
			<div class="school-ratings">
			<span class="star-ratings-sprite">
				<span style="width:<?= $model->school_rate*100/5 ?>%" class="star-ratings-sprite-rating"></span>
			</span>
				<?= number_format(floatval($model->school_rate), 1, '.', ''); ?>
			</div>
		</div>
		<div class="col-sm-3">
			<table class="details">
				<tr>
					<th>
						<?= Yii::t('training/view', 'Start date:'); ?>
					</th>
					<td>
						<?php
						if(is_array($model->startDates)){
							$date = null;
							foreach ($model->startDates as $termin){
								if($termin->start_date>=date('Y-m-d')){
									$date = $termin;
									break;
								}
							}
							echo is_object($date) ? $date->start_text : Yii::t('training/view', 'Contact us');
						}else{
							echo Yii::t('training/view', 'od zaraz');
						}
						?>
					</td>
				</tr>
				<tr>
					<th>
						<?= Yii::t('training/view', 'City:'); ?>
					</th>
					<td>
						<span><?= HtmlPurifier::process($model->address_practice_id != 0 ? $model->addressPractice->city : ($model->address_theory_id != 0 ? $model->addressTheory->city : '-')) ?></span>&nbsp;
					</td>
				</tr>
				<?php if (count($model->aircraft) != 0 || count($model->simulator) != 0) : ?>
				<tr>
					<th>
						<?php
						if (count($model->aircraft) == 0 && count($model->simulator) > 0) {
							echo Yii::t('training/view', 'Simulator:');
						} else
							echo Yii::t('training/view', 'Aircraft:');
						?>
					</th>
					<td>
					<span>
						<?php
						if (count($model->aircraft) == 0 && count($model->simulator) > 0) {
							echo trim($model->simulator[0]->type);
						} else {
							if (count($model->aircraft) > 0) {
								echo trim($model->aircraft[0]->aircraftType->name);
							} else {
								echo "-";
							}
						}
						?>
					</span>&nbsp;
					</td>
				</tr>
				<?php endif; ?>
				<?php if(($model->elearning_hours + $model->theory_hours) > 0): ?>
					<tr>
						<th>
							<?= Yii::t('training/view', 'Teoria:'); ?>
						</th>
						<td>
							<?= ($model->elearning_hours + $model->theory_hours) ?>h
						</td>
					</tr>
				<?php endif; ?>

				<?php if(($model->aircraft_hours + $model->simulator_hours) > 0): ?>
					<tr>
						<th>
							<?= Yii::t('training/view', 'Praktyka:'); ?>
						</th>
						<td>
							<?= ($model->aircraft_hours + $model->simulator_hours) ?>h
						</td>
					</tr>
				<?php endif; ?>
			</table>
		</div>
		<div class="col-sm-3 text-right">
			<h2 class="text-nowrap"><?= number_format(($model->school->country->currency_id!=Yii::$app->params['currency'] ? $converter->convert($model->school->country->currency_id, Yii::$app->params['currency'], $model->price) : $model->price), 0, '.', '<span class="numspan"></span>') ?><span><?= Yii::$app->params['currency'] ?></span></h2>
			<?= Html::a(Yii::t('training/view', 'Szczegóły'), ['training/view', 'id' => $model->id], ['class' => 'btn btn-primary text-uppercase', 'data-pjax'=>'0']) ?>
		</div>
	</div>
	</div>
</div>