common/models/SchoolRates.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base model class for table "school_rates".
 *
 * @property integer $id
 * @property integer $rate
 * @property integer $school_id
 * @property integer $lock
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $deleted_by
 * @property integer $created
 * @property integer $modified
 * @property integer $deleted
 *
 * @property \backend\models\School $school
 */
class SchoolRates extends \common\models\base\SchoolRates{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_merge_recursive(parent::rules(), [
            [['email', 'name'], 'required'],
        ]);
    }
}

frontend/models/SchoolRates.php
<?php

namespace frontend\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base model class for table "school_rates".
 *
 * @property integer $id
 * @property integer $rate
 * @property integer $school_id
 * @property integer $lock
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $deleted_by
 * @property integer $created
 * @property integer $modified
 * @property integer $deleted
 *
 * @property \backend\models\School $school
 */
class SchoolRates extends \common\models\SchoolRates{
    /**
     * @return int
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        $this->sendEmail();
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     *
     * @param string $email the target email address
     * @return boolean whether the email was sent
     */
    public function sendEmail()
    {
        return Yii::$app->mailer->compose()
            ->setTo(\Yii::$app->params['adminEmail'])
            ->setFrom(\Yii::$app->params['supportEmail'])
            ->setSubject(Yii::t('reviews', 'New review'))
            ->setReplyTo([$this->email => $this->name])
            ->setTextBody(implode("\n\n", ['From: '.$this->email . ' <'.$this->name.'>', 'Rate: '.$this->rate, 'Text: '.$this->text]))
            ->send();
    }
}

backend/controllers/SchoolRatesController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\base\SchoolRates;
use backend\models\SchoolRatesSearch;
use backend\models\UserToSchool;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii2mod\rbac\filters\AccessControl;

/**
 * SchoolRatesController implements the CRUD actions for SchoolRates model.
 */
class SchoolRatesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'allowActions' => [
                    // The actions listed here will be allowed to everyone including guests.
                ]
            ],
            'access2' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['update', 'view', 'delete', 'publish'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['update', 'view', 'delete', 'publish'],
                        'matchCallback' => function($rule, $action) {
                            if (\webvimark\modules\UserManagement\models\User::hasRole('school-admin', false))
                            {
                                return UserToSchool::validateUserToSchoolRate(Yii::$app->request->get('id'), Yii::$app->user->id);
                            } else {
                                return true;
                            }
                        }
                    ],
                ],
            ]
        ];
    }

    /**
     * Lists all SchoolRates models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SchoolRatesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (Yii::$app->request->post('hasEditable')) {
            // instantiate your book model for saving
            $ID = Yii::$app->request->post('editableKey');
            $model = SchoolRates::findOne($ID);

            // store a default json response as desired by editable
            $out = Json::encode(['output'=>'', 'message'=>'']);

            // fetch the first entry in posted data (there should only be one entry
            // anyway in this array for an editable submission)
            // - $posted is the posted data for Book without any indexes
            // - $post is the converted array for single model validation
            $posted = current($_POST['SchoolRates']);
            $post = ['SchoolRates' => $posted];

            // load model like any single model validation
            if ($model->load($post)) {
                // can save model or do something before saving model
                $model->save();

                // custom output to return to be displayed as the editable grid cell
                // data. Normally this is empty - whereby whatever value is edited by
                // in the input by user is updated automatically.
                $output = '';

                // specific use case where you need to validate a specific
                // editable column posted when you have more than one
                // EditableColumn in the grid view. We evaluate here a
                // check to see if buy_amount was posted for the Book model

                if (isset($posted['published'])) {
                $output = $model->published == 1 ? Yii::t('backend', 'Yes') : Yii::t('backend', 'No');
                }


                // similarly you can check if the name attribute was posted as well
                // if (isset($posted['name'])) {
                // $output = ''; // process as you need
                // }
                $out = Json::encode(['output'=>$output, 'message'=>'']);
            }
            // return ajax json encoded response and exit
            echo $out;
            return;
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSubcat1() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cat_id = $parents[0];
                if (!empty($_POST['depdrop_params'])) {
                    $params = $_POST['depdrop_params'];
                }

                $out = \backend\models\base\Training::find()->where(['=', 'school_id', $cat_id])->orderBy('id')->asArray()->all();

                // the getSubCatList1 function will query the database based on the
                // cat_id, param1, param2 and return an array like below:
                // [
                //    'group1'=>[
                //        ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
                //        ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
                //    ],
                //    'group2'=>[
                //        ['id'=>'<sub-cat-id-3>', 'name'=>'<sub-cat-name3>'],
                //        ['id'=>'<sub-cat-id-4>', 'name'=>'<sub-cat-name4>']
                //    ]
                // ]


                $selected = $out[0];
                // the getDefaultSubCat function will query the database
                // and return the default sub cat for the cat_id

                echo Json::encode(['output'=>$out, 'selected'=>$selected]);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }

    /**
     * Displays a single SchoolRates model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SchoolRates model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SchoolRates();

        if ($model->loadAll(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing SchoolRates model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->loadAll(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Publiush / Unpublish an existing SchoolRates model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionPublish($id)
    {
        $model = $this->findModel($id);
        $model->published = $model->published==1 ? 0 : 1;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing SchoolRates model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    
    /**
     * Finds the SchoolRates model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SchoolRates the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SchoolRates::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('schoolrates', 'The requested page does not exist.'));
        }
    }
}

backend/views/school-rates/_form.php
<?php

//use yii\helpers\Html;
use webvimark\modules\UserManagement\components\GhostHtml as Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\widgets\DepDrop;

/* @var $this yii\web\View */
/* @var $model backend\models\base\SchoolRates */
/* @var $form yii\widgets\ActiveForm */

$school_admin = \webvimark\modules\UserManagement\models\User::hasRole('school-admin', false);

?>

<div class="school-rates-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'rate')->dropDownList([0 => '0', 1 => '1', 2 => '2', 3 => '3', 4 => '4', 5 => '5'], ['disabled'=>$school_admin]); ?>

    <?php

        echo $form->field($model, 'school_id')->dropDownList(\yii\helpers\ArrayHelper::map(\backend\models\base\School::find()->active()->orderBy('id')->asArray()->all(), 'id', 'name'), ['id'=>'cat1-id', 'disabled'=>$school_admin]);


        echo $form->field($model, 'training_id')->widget(DepDrop::classname(), [
            'type'=>DepDrop::TYPE_SELECT2,
            'data'=>\yii\helpers\ArrayHelper::map(\backend\models\base\Training::find()->where(['=', 'training.school_id', $model->school_id])->active()->orderBy('id')->all(), 'id', function($ar, $dv){return $ar->licenseType->license.' ('.$ar->price.'zł)';}),
            'options'=>['id'=>'subcat1-id', 'disabled'=>$school_admin],
            'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
            'pluginOptions'=>[
                'depends'=>['cat1-id'],
                'placeholder'=>'Select ...',
                'url'=>Url::to(['/school-rates/subcat1'])
            ]
        ]);

    ?>


    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'placeholder' => 'Name', 'disabled'=>$school_admin]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'placeholder' => 'Email', 'disabled'=>$school_admin]) ?>

    <?php if (!$school_admin) echo $form->field($model, 'user_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\common\models\User::find()->orderBy('id')->asArray()->all(), 'id', 'email'),
        'options' => ['placeholder' => Yii::t('backend/school-rates', 'Choose User')],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'text')->textarea(['rows' => 6, 'disabled'=>$school_admin]) ?>

    <?= $form->field($model, 'lock', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'published')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend/school-rates', 'Create') : Yii::t('backend/school-rates', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/school-rates/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

backend/views/school-rates/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend/models\SchoolRatesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-school-rates-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'rate')->textInput(['placeholder' => 'Rate']) ?>

    <?= $form->field($model, 'school_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\backend\models\base\School::find()->orderBy('id')->asArray()->all(), 'id', 'name'),
        'options' => ['placeholder' => Yii::t('schoolrates', 'Choose School')],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'training_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\backend\models\base\Training::find()->orderBy('id')->asArray()->all(), 'id', 'name'),
        'options' => ['placeholder' => Yii::t('schoolrates', 'Choose Training')],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'placeholder' => 'Name']) ?>

    <?php /* echo $form->field($model, 'email')->textInput(['maxlength' => true, 'placeholder' => 'Email']) */ ?>

    <?php /* echo $form->field($model, 'user_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\backend\models\base\User::find()->orderBy('id')->asArray()->all(), 'id', 'username'),
        'options' => ['placeholder' => Yii::t('schoolrates', 'Choose User')],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); */ ?>

    <?php /* echo $form->field($model, 'text')->textarea(['rows' => 6]) */ ?>

    <?php /* echo $form->field($model, 'lock', ['template' => '{input}'])->textInput(['style' => 'display:none']); */ ?>

    <?php /* echo $form->field($model, 'published')->checkbox() */ ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('schoolrates', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('schoolrates', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/school-rates/create.php
<?php

//use yii\helpers\Html;
use webvimark\modules\UserManagement\components\GhostHtml as Html;


/* @var $this yii\web\View */
/* @var $model backend\models\base\SchoolRates */

$this->title = Yii::t('schoolrates', 'Create School Rates');
$this->params['breadcrumbs'][] = ['label' => Yii::t('schoolrates', 'School Rates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="school-rates-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/school-rates/index.php
<?php

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

//use yii\helpers\Html;
use webvimark\modules\UserManagement\components\GhostHtml as Html;
use kartik\export\ExportMenu;
use kartik\grid\GridView;
use kartik\popover\PopoverX;

$school_admin = \webvimark\modules\UserManagement\models\User::hasRole('school-admin', false);

$this->title = Yii::t('backend/school-rates', 'School Rates');
$this->params['breadcrumbs'][] = $this->title;
$this->params['page_header'] = $this->title;
$this->params['page_subheader'] = Yii::t('backend/school-rates', 'School Rate');
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
$this->registerJs($search);
?>
<div class="col-lg-12 col-md-12 school-rates-index">


    <p>
        <?= Html::a(Yii::t('backend/school-rates', 'Create School Rates'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php

    if ($school_admin) {
        $gridColumn = [
            ['class' => 'yii\grid\SerialColumn'],
            ['attribute' => 'id', 'visible' => false],
            [
                'attribute'=>'rate',
                'hAlign'=>'right',
                'vAlign'=>'middle',
                'pageSummary'=>true,
                'width'=>'70px',
            ],
            [
                'attribute' => 'school_id',
                'label' => Yii::t('backend/school-rates', 'School'),
                'value' => function($model){
                    return $model->school->name;
                },
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => \yii\helpers\ArrayHelper::map(\backend\models\School::find()->active()->asArray()->all(), 'id', 'name'),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'School', 'id' => 'grid--school_id']
            ],
            [
                'attribute'=>'name',
                'hAlign'=>'right',
                'vAlign'=>'middle',
                'pageSummary'=>true
            ],
            'email:email',
            [
                'attribute' => 'user_id',
                'label' => Yii::t('backend/school-rates', 'User logged'),
                'value' => function($model){
                    return $model->user_id != null ? $model->user->email : 'not set';
                },
            ],
            [
                'attribute'=>'text',
                'hAlign'=>'left',
                'vAlign'=>'top',
                'width'=>'30%',
                'pageSummary'=>true
            ],
        ];
    } else {
        $gridColumn = [
            ['class' => 'yii\grid\SerialColumn'],
            ['attribute' => 'id', 'visible' => false],
            [
                'class'=>'kartik\grid\EditableColumn',
                'attribute'=>'rate',
                'editableOptions'=>[
                    'inputType' => \kartik\editable\Editable::INPUT_DROPDOWN_LIST,
                    'data' => [0 => '0', 1 => '1', 2 => '2', 3 => '3', 4 => '4', 5 => '5'],
                ],
                'hAlign'=>'right',
                'vAlign'=>'middle',
                'pageSummary'=>true,
                'width'=>'70px',
            ],
            [
                'attribute' => 'school_id',
                'label' => Yii::t('backend/school-rates', 'School'),
                'value' => function($model){
                    return $model->school->name;
                },
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => \yii\helpers\ArrayHelper::map(\backend\models\School::find()->active()->asArray()->all(), 'id', 'name'),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'School', 'id' => 'grid--school_id']
            ],
            [
                'class'=>'kartik\grid\EditableColumn',
                'attribute'=>'name',
                'editableOptions'=>[
                    'inputType'=>\kartik\editable\Editable::INPUT_TEXT
                ],
                'hAlign'=>'right',
                'vAlign'=>'middle',
                'pageSummary'=>true
            ],
            'email:email',
            [
                'attribute' => 'user_id',
                'label' => Yii::t('backend/school-rates', 'User'),
                'value' => function($model){
                    return $model->user_id != null ? $model->user->email : Yii::t('backend', 'not set');
                },
            ],
            [
                'class'=>'kartik\grid\EditableColumn',
                'attribute'=>'text',
                'editableOptions'=>[
                    'inputType'=>\kartik\editable\Editable::INPUT_TEXT
                ],
                'hAlign'=>'left',
                'vAlign'=>'top',
                'width'=>'30%',
                'pageSummary'=>true
            ],
        ];
    }
    $gridColumn = array_merge($gridColumn, [
        ['attribute' => 'lock', 'visible' => false],
        [
            'class'=>'kartik\grid\EditableColumn',
            'attribute'=>'published',
            'editableOptions'=>[
                'inputType'=>\kartik\editable\Editable::INPUT_CHECKBOX,
                'header'=>'Published',
                'placement'=>PopoverX::ALIGN_LEFT,
            ],
            'value'=>function($data){ return ($data->published==1 ? Yii::t('backend', 'Yes'):Yii::t('backend', 'No')); },
            'hAlign'=>'right',
            'vAlign'=>'middle',
            'width'=>'50px',
            'pageSummary'=>true,
            'filterType' => GridView::FILTER_SELECT2,
            'filter' => [0=>Yii::t('backend', 'No'), 1=>Yii::t('backend', 'Yes')],
            'filterWidgetOptions' => [
                'pluginOptions' => ['allowClear' => true],
            ],
            'filterInputOptions' => ['placeholder' => 'Published', 'id' => 'grid-school-rates-search-published']
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view} {update} {delete}',
            'buttons' => [
                'view'=>function($url,$model,$key){
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['school-rates/view', 'id'=>$model->id], ['title'=>Yii::t('backend/school-rates', 'View')]);
                },
                'update'=>function($url,$model,$key){
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['school-rates/update', 'id'=>$model->id], ['title'=>Yii::t('backend/school-rates', 'Update')]);
                },
                'delete'=>function($url,$model,$key){
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['school-rates/delete', 'id'=>$model->id], ['title'=>Yii::t('backend/school-rates', 'Delete'), 'data-method'=>'post', 'data-confirm'=>Yii::t('backend/school-rates', 'Are you sure you want to delete this item?'), 'aria-label'=>Yii::t('backend/school-rates', 'Delete')]);
                },
            ],
        ],
    ]);
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumn,
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-school']],
        'resizableColumns'=>true,
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . Html::encode($this->title),
        ],
        'export' => false,
        // your toolbar can include the additional full export menu

        'toolbar' => [
            '{toggleData}',
        ],
    ]); ?>

</div>

<?php
/*
$this->registerJs("

		$('.kv-editable').click(function(e){
			$('.kv-editable-popover.in').not('#'+$(this).attr('id').replace('-targ', '')+'-popover .kv-editable-popover.in').removeClass('in').hide();
			return true;
		});
	");
*/
?>

backend/views/school-rates/update.php
<?php

//use yii\helpers\Html;
use webvimark\modules\UserManagement\components\GhostHtml as Html;

/* @var $this yii\web\View */
/* @var $model backend\models\base\SchoolRates */

$this->title = Yii::t('backend/school-rates', 'Update {modelClass}: ', [
    'modelClass' => 'School Rates',
]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend/school-rates', 'School Rates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend/school-rates', 'Update');
?>
<div class="school-rates-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/school-rates/view.php
<?php

//use yii\helpers\Html;
use webvimark\modules\UserManagement\components\GhostHtml as Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model backend\models\base\SchoolRates */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend/school-rates', 'School Rates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['page_header'] = $this->title;
$this->params['page_subheader'] = Yii::t('backend/school-rates', 'School Rate');
?>
<div class="school-rates-view">

    <div class="row">
        <div class="col-sm-9">

        </div>
        <div class="col-sm-3 text-right" style="margin-top: 15px">
            
            <?= Html::a(Yii::t('backend/school-rates', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('backend/school-rates', 'Change visibility'), ['publish', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('backend/school-rates', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('backend/school-rates', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ])
            ?>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'rate',
        [
            'attribute' => 'school.name',
            'label' => Yii::t('backend/school-rates', 'School'),
        ],
        [
            'attribute' => 'training.name',
            'label' => Yii::t('backend/school-rates', 'Training'),
        ],
        'name',
        'email:email',
        [
            'attribute' => 'user.email',
            'label' => Yii::t('backend/school-rates', 'User'),
        ],
        'text:ntext',
        ['attribute' => 'lock', 'visible' => false],
        'published',
        [
            'attribute' => 'published',
            'value' => function($model){ return $model->published==1 ? Yii::t('backend', 'Yes') : Yii::t('backend', 'No');}
        ],
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>
</div>