common/models/LicenseType.php
<?php

namespace common\models;

use Yii;
use \common\models\base\LicenseType as BaseLicenseType;

/**
 * This is the model class for table "license_type".
 */
class LicenseType extends BaseLicenseType
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['license'], 'required'],
            [['lock', 'created_by', 'updated_by', 'deleted_by', 'created', 'modified', 'deleted', 'order'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['license'], 'string', 'max' => 255],
            [['lock'], 'default', 'value' => '0'],
            [['lock'], 'mootensai\components\OptimisticLockValidator']
        ]);
    }
	
	public function getLicenceDescription(){
		return $this->description;
	}

	public function getTLicenceDescription(){
        if(!$description = \Yii::$app->cache->get(__CLASS__.'/description'.$this -> id.\Yii::$app->language)){
            $description = $this -> hasTranslation() ? $this -> translate() -> description : $this -> description;
            \Yii::$app->cache->set(__CLASS__.'/description'.$this -> id.\Yii::$app->language, $description, 3600*24);
        }

        return $description;
	}

	public function getTText(){
        if(!$text = \Yii::$app->cache->get(__CLASS__.'/text'.$this -> id.\Yii::$app->language)){
            $text = $this -> hasTranslation() ? $this -> translate() -> text : $this -> text;
            \Yii::$app->cache->set(__CLASS__.'/text'.$this -> id.\Yii::$app->language, $text, 3600*24);
        }

        return $text;
	}

	public function getTRequirements(){
        if(!$requirements = \Yii::$app->cache->get(__CLASS__.'/requirements'.$this -> id.\Yii::$app->language)){
            $requirements = $this -> hasTranslation() ? $this -> translate() -> requirements : $this -> requirements;
            \Yii::$app->cache->set(__CLASS__.'/requirements'.$this -> id.\Yii::$app->language, $requirements, 3600*24);
        }

        return $requirements;
	}
	
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii2mod\rbac\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
	
	public $layout = 'king';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'allowActions' => [
                    'login', 'error'
                    // The actions listed here will be allowed to everyone including guests.
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\TrainingSearch,
    common\models\User,
    common\models\Profile,
    common\models\authClient;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'oAuthSuccess'],
                'successUrl' => \yii\helpers\Url::to(['site/index']),
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TrainingSearch();	
        return $this->render('index', [
            'searchModel' => $searchModel
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionUserConfirmation()
    {
        if ($user = User::findOne(['=', 'confirmation_token', Yii::$app->request->get('token', '0')])) {
            $header = Yii::t('registration/confirmationEmail', 'Thank you for confirming your email address.');
            $text = Yii::t('registration/confirmationEmail', 'Now you can login to BestPilot and find your training.');
            $status = 'success';
        } else {
            $header = Yii::t('registration/confirmationEmail', 'Your email is already confirmed.');
            $text = Yii::t('registration/confirmationEmail', 'You can login to BestPilot and find your training.');
            $status = 'error';
        }
        return $this->render('userConfirmation', [
            'header' => $header,
            'text' => $text,
            'status' => $status
        ]);
    }

    public function oAuthSuccess($client) {
        // get user data from client
        $userAttributes = $client->getUserAttributes();
        if($client->getId()=='google')
            $userAttributes['email'] = $userAttributes['emails'][0]['value'];

        if(!$find = authClient::find()->where(['authClient_name'=>$client->getId(), 'authClient_id'=>$userAttributes['id']])->one()){
            if (!$user = User::findByUsername($userAttributes['email'])){
                $model = new SignupForm();
                $model->email = $userAttributes['email'];
                $model->password = \Yii::$app->security->generateRandomString(8);
                $model->password_repeat = $model->password;

                if($model->signup()){
                    $user = User::findByUsername($model->email);

                    if(!$profile = Profile::findOne($user->id))
                        $profile = new Profile();

                    if($user->status != User::STATUS_ACTIVE){
                        $user->status = User::STATUS_ACTIVE;
                        $user->save(false);
                    }

                    $profile->username = $client->getId()=='google' ? $userAttributes['displayName'] : $userAttributes['name'];
                    $profile->user_id = $user->id;
                    $profile->save(false);
                }
            }

            $find = new authClient();
            $find->authClient_name = $client->getId();
            $find->authClient_id = $userAttributes['id'];
            $find->user_id = $user->id;
        }

        $find->last_login = date('Y-m-d H:i:s');
        $find->save();

        $modelLoginForm = new LoginForm();
        $modelLoginForm->username = $find->user->email;
        $modelLoginForm->loginSocial();
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['office/index']);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', Yii::t('pages', 'Thank you for contacting us. We will respond to you as soon as possible.'));
            } else {
                Yii::$app->session->setFlash('error', Yii::t('pages', 'There was an error sending email.'));
            }

            return $this->redirect(\Yii::$app->request->getReferrer());
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) { //funkcja signup wysyła maila do usera
                Yii::$app->session->setFlash('success', Yii::t('pages', 'Check your email for further instructions.'));
                return $this->redirect(['site/index']);
                /*
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect(['site/index']);
                }
                */
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', Yii::t('pages', 'Check your email for further instructions.'));
            } else {
                Yii::$app->session->setFlash('error', Yii::t('pages', 'Sorry, we are unable to reset password for email provided.'));
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', Yii::t('pages', 'New password was saved.'));

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = Yii::t('pages', 'About');
?>
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-sm-7 contact_form">
            <h1 class="text-blue"><?= Html::encode($this->title) ?></h1>
            <div>
                <?php if (Yii::$app->language=='pl'): ?>
                <p><strong>BestPilot.com</strong> to platforma łącząca szkoły latania z przyszłymi i aktualnymi pilotami.</p>
                <p>
                    Jeśli marzysz, aby zostać pilotem samolotu <strong>BestPilot.com</strong> to idealne miejsce! Znajdziesz tu zarówno
                    szkolenia do licencji turystycznej PPL(A), jak również oferty szkoleń zawodowych, "od zera do ATPL(A)"
                    oraz oferty budowania nalotu. Dopasuj parametry szkolenia do swoich potrzeb. Cena,
                    wiek samolotu czy lokalizacja to tylko niektóre z możliwości.
                </p>

                <p>System ocen umożliwia zapoznanie się z opiniami innych uczestników szkoleń. Ty również możesz ocenić wybraną szkołę.</p>

                <p>Nasz cel: <strong>dostarczanie ofert szkoleń samolotowych dopasowanych do potrzeb przyszłych i aktualnych pilotów.</strong></p>

                <h3>Korzyści dla pilotów:</h3>
                <ul>
                    <li>dostęp do limitowanych szkoleń</li>
                    <li>atrakcyjne oferty budowania nalotu</li>
                    <li>zniżki i promocje</li>
                </ul>

                <h3>Korzyści dla szkoły lotniczej:</h3>
                <ul>
                    <li>promowanie oferty</li>
                    <li>dostęp sprecyzowanej grupy docelowej</li>
                </ul>
                <p>Promujmy wspólnie rozwój lotnictwa w Polsce i na świecie.</p>
                <p><strong>BestPilot.com</strong> należy do grupy EVIONICA.</p>
                <?php elseif (Yii::$app->language=='en'): ?>
                    <p><strong>BestPilot.com</strong> is a platform connecting flight schools with current and future pilots.</p>
                    <p>
                        If your dream is to become a pilot <strong>BestPilot.com</strong> is perfect for you! You can find here not only Private Pilot License
                        PPL(A) trainings, but also professional courses, from zero to ATPL(A) programs and time building offers. You can
                        personalize your training and make sure that it suits you best. Price, aircraft manufacturing year or localization are just some possibilities.
                    </p>

                    <p>Thanks to the reviews you can get to know other students’ opinions. You can also rate the flight school and write a comment</p>

                    <p>Our goal:  <strong>deliver the best, personalized offers for current and future pilots.</strong></p>

                    <h3>Benefits for pilots:</h3>
                    <ul>
                        <li>Access to limited offers</li>
                        <li>Attractive time building offers</li>
                        <li>Discounts and rebates</li>
                    </ul>

                    <h3>Benefits for flight academies:</h3>
                    <ul>
                        <li>Promoting offers</li>
                        <li>Access to specific target group</li>
                    </ul>
                    <p>Let’s promote aviation development in Poland and in the world together.</p>
                    <p><strong>BestPilot.com</strong> belongs to EVIONICA group.</p>
                <?php endif; ?>
            </div>
        </div>
    </div>

</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('pages', 'Kontakt');
?>
<div class="container">
    <div class="row">
        <div class="col-lg-5 col-sm-7 contact_form">
            <h1 class="text-blue"><?= Html::encode($this->title) ?></h1>

            <h3 class="text-blue">BestPilot</h3>
            <p class="text-blue address"><?= Yii::t('Kontakt', 'al. Stanów Zjednoczonych 51/620') ?> <br /><?= Yii::t('Kontakt', '04-028 Warsaw') ?></p>
            <p class="text-blue"><?= Yii::t('Kontakt', 'VAT-EU: {number}', ['number'=>'5441426877']) ?><br /><?= Yii::t('Kontakt', 'Commercial Registry No.: {number}', ['number'=>'147066893']) ?></p>

            <div class="visible-xs mobile-buttons-call">
                <a href="tel:+48570920787" class="btn btn-default btn-lg btn-block phone">+48 570 920 787</a>
                <a href="mailto:office@bestpilot.com" class="btn btn-default btn-lg btn-block phone">office@bestpilot.com</a>
                <a href="https://www.facebook.com/bestpilotcom/" class="btn btn-default btn-lg btn-block phone" target="_blank"><span class="icon-facebook"></span> Facebook</a>
            </div>

            <?php $form = ActiveForm::begin(['id' => 'contact-form', 'validateOnBlur'=>false, 'validateOnChange'=>false]); ?>

                <?= Html::tag('h3', Yii::t('page', 'Masz pytanie?'), ['class'=>'text-blue']) ?>

                <?= $form->field($model, 'name', ['inputOptions' => ['placeholder' => $model->getAttributeLabel('name'), 'class'=>'input-lg form-control']])
                    ->label(false)
                    ->textInput() ?>

                <?= $form->field($model, 'email', ['inputOptions' => ['placeholder' => $model->getAttributeLabel('email'), 'class'=>'input-lg form-control']])
                    ->label(false)
                    ->textInput() ?>

                <?= $form->field($model, 'body', ['inputOptions' => ['placeholder' => $model->getAttributeLabel('body'), 'class'=>'input-lg form-control']])
                    ->label(false)
                    ->textarea(['rows' => 6]) ?>

                <div class="fo rm-group">
                    <?= Html::submitButton(Yii::t('pages', 'Wyślij'), ['class' => 'btn btn-primary btn-lg', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-lg-3 col-sm-5 col-lg-offset-2 phone-details contact_form hidden-xs">
            <a href="tel:+48570920787" class="btn btn-default btn-lg btn-block phone">+48 570 920 787</a>
            <a href="mailto:office@bestpilot.com" class="btn btn-default btn-lg btn-block phone">office@bestpilot.com</a>
            <a href="https://www.facebook.com/bestpilotcom/" class="btn btn-default btn-lg btn-block phone"><span class="icon-facebook"></span> Facebook</a>
        </div>
    </div>

</div>
<div id="mapa-div" style="height:500px; padding:0px;"></div>

<?php

$this->registerJs('    
    function mapBaloon(){
          var contentString = \'<div id="content">\'+
              \'<div id="bodyContent" style="padding:15px;">\'+
                  \'<h3 class="text-blue">BestPilot</h3><br />\'+
                  \'<p class="text-blue">al. Stanów Zjednoczonych 51/620<br />\'+
                  \'04-028 Warsaw, Poland</p>\'+
              \'</div>\'+
          \'</div>\';
          
          /*var geocoder = new google.maps.Geocoder();          
          var address = $("p.address").text();
          geocoder.geocode({\'address\': address}, function(results, status) {
                if (status === \'OK\') {
                    googlemap.setCenter(results[0].geometry.location);                    
                    var infowindow = new google.maps.InfoWindow({
                        content: contentString,
                        maxWidth: 350,
                        position: results[0].geometry.location,
                    });                    
                    infowindow.open(googlemap);                     
                    google.maps.event.addListener(googlemap, \'click\', function() {
                        return false;
                    });
                }
                
                console.log(results);
          });*/
          
          googlemap.setCenter(new google.maps.LatLng(52.237455,21.079164));                    
          var infowindow = new google.maps.InfoWindow({
              content: contentString,
              maxWidth: 350,
              position: new google.maps.LatLng(52.237455,21.079164),
          });                    
          infowindow.open(googlemap);                     
          google.maps.event.addListener(googlemap, \'click\', function() {
              return false;
          });             
    }    
', \yii\web\View::POS_HEAD);

$this->registerJs('mapInit(15, "mapBaloon()");');

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="info-page extraTopMargin">
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="site-error">

                <h1><?= Html::encode($this->title) ?></h1>

                <div class="alert alert-danger extraTopMargin">
                    <?= nl2br(Html::encode($message)) ?>
                </div>

                <p>
                    The above error occurred while the Web server was processing your request.
                </p>
                <p>
                    Please contact us if you think this is a server error. Thank you.
                </p>

            </div>
        </div>
    </div>
</div>
</div>

frontend/views/site/index.php
<?php
	use twofox\select2\Select2;
	use common\models\LicenseType;
	use kartik\widgets\ActiveForm;
	use yii\helpers\Html,
		yii\helpers\ArrayHelper;


	$this->title = Yii::t('page/home', 'BestPilot');
		
	$LicenseType = LicenseType::find()->where(['deleted'=>0])->orderBy('order DESC')->all();
	$Country = backend\models\Country::find()->where(['deleted'=>0])->orderBy('country ASC')->all();

	$countryArr = ArrayHelper::map($Country, 'id', 'ttitle');
	asort($countryArr, SORT_STRING);

	$searchModel->license_id = $LicenseType[0]->id;
?>
<div class="site-index">
    <div class="jumbotron" style="height: 891px;">
        <div class="container"> 
	        <h1><?= \Yii::t('site/index', 'Zostań najlepszym pilotem.') ?></h1>
	        <h2><?= \Yii::t('site/index', 'Znajdź szkolenie dla siebie.') ?></h2>
	        <div class="row">
	        	<?php $form = ActiveForm::begin([
					'action' => ['training/index'],
					'method' => 'get',
					'options'=>['id'=>'training-search-form']
				]); ?>
				<div class="col-lg-3 col-sm-4 col-xs-12">
				<?= $form->field($searchModel, 'license_id')->label(false)->widget(Select2::classname(), [
					'hideSearch' => true,
					'data' => ArrayHelper::map(ArrayHelper::toArray($LicenseType), 'id', 'license'),
					'pluginOptions' => [
						'allowClear' => false,
						'dropdownParent'=> '.jumbotron'
						/*'initSelection' => new JsExpression('function(){
							wiIndwxResize();
						}')*/
					],
				]); ?>
				</div>
				<div class="col-lg-3 col-sm-4 col-xs-12">
					<?=
					Html::hiddenInput('ww', '').
					$form->field($searchModel, 'country_id')->label(false)->widget(Select2::classname(), [
						'hideSearch' => true,
						'data' => $countryArr,
						'options' => [
							'placeholder' => Yii::t('site/index', 'wybierz region')
						],
						'pluginOptions' => [
							'allowClear' => false,
							'dropdownParent'=> '.jumbotron'
							/*'initSelection' => new JsExpression('function(){
								wiIndwxResize();
							}')*/
						],
					]); ?>
				</div>
				<div class="col-lg-3 col-sm-4 col-xs-12">
	        		<?= Html::submitButton(Yii::t('site/index', '<span class="glyphicon glyphicon-search"></span> SZUKAJ'), ['class' => 'btn btn-warning btn-block text-uppercase']) ?>
	        	</div>
	        	<?php ActiveForm::end(); ?>
	        </div>
        </div>
    </div>

    <div class="container base-info">
        <div class="row">
        	<div class="col-lg-3 col-sm-6">
        		<div class="panel panel-default">
					<div class="panel-heading clearfix"><h1><?= \Yii::t('site/index', '103') ?></h1><h3><?= \Yii::t('site/index', 'Wyszkolonych<br />pilotów') ?></h3></div>
					<div class="panel-body">
					    <?= \Yii::t('site/index', 'Dołącz do grona najlepszych pilotów.') ?>
					</div>
				</div>
        	</div>
        	<div class="col-lg-3 col-sm-6">
        		<div class="panel panel-default">
					<div class="panel-heading clearfix"><h1><?= \Yii::t('site/index', '52') ?></h1><h3><?= \Yii::t('site/index', 'Szkoły<br />latania') ?></h3></div>
					<div class="panel-body">
					    <?= \Yii::t('site/index', 'Współpracujemy tylko ze sprawdzo- nymi ośrodkami szkolenia lotniczego.') ?>
					</div>
				</div>
        	</div>
        	<div class="col-lg-3 col-sm-6">
        		<div class="panel panel-default">
					<div class="panel-heading clearfix"><h1><span class="icon-gwarancja_icon"></span></h1><h3><?= \Yii::t('site/index', 'Gwarancja') ?></h3></div>
					<div class="panel-body">
					    <?= \Yii::t('site/index', 'Zyskujesz ubezpieczenie i opiekę na cały czas trwania szkolenia.') ?>
					</div>
				</div>
        	</div>
        	<div class="col-lg-3 col-sm-6">
        		<div class="panel panel-default">
					<div class="panel-heading clearfix"><h1><span class="icon-unikatowe-szkolenia_v2"></span></h1><h3><?= \Yii::t('site/index', 'Unikatowe<br />szkolenia') ?></h3></div>
					<div class="panel-body">
					    <?= \Yii::t('site/index', 'Jako członek BestPilot masz dostęp do specjalnych ofert.') ?>
					</div>
				</div>
        	</div>
        </div>
    </div>
</div>

<div class="info-data">
	<div class="container">
		<div class="clearfix">
			<?= Html::tag('h1', \Yii::t('site/index', 'Szkolenia'), ['class'=>'pull-left']) ?>
			<?= Html::a(\Yii::t('site/index', 'Pokaż wszystkie <span class="glyphicon glyphicon-menu-right"></span>'), ['license/index'], ['class'=>'pull-right strong']) ?>
		</div>
		<div class="row first-row">
			<?php foreach ($LicenseType as $key => $value): if($key>3) break; ?>
			<div class="col-lg-4 col-sm-6 <?= $key==3?'visible-sm':'' ?>">
        		<div class="panel panel-default">
					<div class="panel-heading clearfix"><?= Html::tag('h3', $value->license) ?></div>
					<div class="panel-body">
					    <?= $value->tLicenceDescription ?>
					</div>
					<div class="panel-footer text-center"><?= Html::a(\Yii::t('site/index', 'Szczegóły'), ['license/view', 'id'=>$value->id], ['class'=>'text-uppercase btn btn-primary']) ?></div>
				</div>
        	</div>
			<?php endforeach; ?>
		</div>
		
		<div class="clearfix">
			<?= Html::tag('h1', \Yii::t('site/index', 'Oni skorzystali')) ?>
		</div>
		
		<div class="row second-row">
			<div class="col-lg-5 col-sm-6">
        		<div class="panel panel-default">
					<?php if (Yii::$app->language=='pl'): ?>
						<div class="panel-heading clearfix">
							<h3>Paweł</h3>
							<p class="text-uppercase">Szkolenie PPL(A) - SmartAero</p>
						</div>
						<div class="panel-body">
							<em>W szkole SmartAero robiłem licencję PPL(A).  Według mnie to najlepsza szkoła lotnicza w Warszawie. Instruktorzy chętnie służyli pomocą i odpowiadali na wszystkie pytania. Stan techniczny samolotów oceniam jako znakomity. Zdecydowanie polecam!</em>
						</div>
					<?php elseif (Yii::$app->language=='en'): ?>
						<div class="panel-heading clearfix">
							<h3>Paweł</h3>
							<p class="text-uppercase">Training PPL(A) - SmartAero</p>
						</div>
						<div class="panel-body">
							<em>I have finished PPL(A) training in SmartAero. In my opinion it is the best flight school in Warsaw. Instructors were always ready to help and answer our questions. Technical condition of aircrafts was excellent. I will definitely recommend this school!</em>
						</div>
					<?php endif; ?>
				</div>
        	</div>
			<div class="col-lg-5 col-lg-offset-2 col-sm-6">
        		<div class="panel panel-default">
					<?php if (Yii::$app->language=='pl'): ?>
						<div class="panel-heading clearfix">
							<h3>Anna</h3>
							<p class="text-uppercase">Szkolenie ATPL(A) teoria - Adriana Aviation</p>
						</div>
						<div class="panel-body">
							<em>Szkolenie przebiegło bardzo sprawnie. Wykłady były bardzo interesujące i profesjonalnie zorganizowane. Duży plus dla szkoły za komputerowe kursy, dzięki którym można uczyć się również na odległość.</em>
						</div>
					<?php elseif (Yii::$app->language=='en'): ?>
						<div class="panel-heading clearfix">
							<h3>Anna</h3>
							<p class="text-uppercase">Training ATPL(A) theory - Adriana Aviation</p>
						</div>
						<div class="panel-body">
							<em>Training went very well. Lectures were very interesting and professionally organized. Computer courses are big advantage, thanks to them I was able to learn at home.</em>
						</div>
					<?php endif; ?>
				</div>
        	</div>
		</div>
	</div>
</div>